name: gargi_mata
description: "This project is a spiritual platform that provides features like Bhajan, Vidhi, Panchang, Samagri, Mantra, Daan Patr, Gallery, Join, and History. It helps users access devotional songs, ritual guides, important dates, sacred items, and donation options, all in one place."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:  # Add this line
    sdk: flutter
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.2
  flutter_dotenv: ^5.1.0
  carousel_slider: ^5.0.0
  flutter_bloc:
  equatable: ^2.0.5
  get_it: ^8.0.3
  firebase_core:
  flutter_svg: ^2.0.17
  table_calendar:
  just_audio: ^0.9.46
  url_launcher: ^6.3.1
  firebase_database:
  cloud_firestore: ^5.6.5
  intl:
  upi_pay: ^1.1.0
  marquee: ^2.3.0
  qr_flutter: ^4.1.0
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/fonts/
    - assets/images/
    - assets/videos/


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
