// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVR1wxL_gQJDar7JOtJmeWqQ9XQlAj4jo',
    appId: '1:273773587800:android:b7042cecf614088a62492d',
    messagingSenderId: '273773587800',
    projectId: 'gargimata-d749f',
    databaseURL: 'https://gargimata-d749f-default-rtdb.firebaseio.com',
    storageBucket: 'gargimata-d749f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHd8KIvmh2eJ_7dSS0gpKotXDFj3zLBDQ',
    appId: '1:273773587800:ios:157f90e97dccd3d462492d',
    messagingSenderId: '273773587800',
    projectId: 'gargimata-d749f',
    databaseURL: 'https://gargimata-d749f-default-rtdb.firebaseio.com',
    storageBucket: 'gargimata-d749f.firebasestorage.app',
    iosBundleId: 'app.gargi.mata.gargiMata',
  );
}
